baseURL = "https://angela-grow.com/"
languageCode = "en-us"
title = "angela-grow"
theme = "til"

[params]
  dateFormat = ":date_long"
  showGraph = false

[params.author]
  name = "Angela"

[params.footer]
  showThemeCredit = false

[[menus.main]]
  name = "Personal"
  url = "/personal/"
  weight = 1

[[menus.main]]
  name = "Work"
  url = "/work/"
  weight = 2

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 3